### ISSUE TITLE
No information if luxmed account is blocked

### ISSUE THREAD

**Issue by gelmiro** [dyrkin/luxmed-booking-service#6]
Hi,
I had situation when my luxmed account has been blocked. (maybe to many periodic request when monitoring is working?) I had active one monitoring and I didn't know that bot have problem with login due to moment when I tried login via browser to check something. I think that bot can observe when account is blocked, or password is incorrect from some reason and inform user about this.

**Comment by dyrkin** [comment]
First of all, I'm sorry to hear this.

Monitoring initializes in such way:
When user creates monitoring app creates a scheduled task with:

- **delay** - some random value in seconds between 0 and 10.minutes.toSeconds
- **period** - some random value between 10.minutes.toSeconds and 15.minutes.toSeconds

So, monitoring never starts immediately. Usually it's delayed and period of repeated queries can't be less than 10 minutes. I did this because I don't want to DDOS luxmed server. 

**I never had an issue with blocked account.**
Could you please attach some logs and I'll add support for notifying users when account is blocked.

Or if you know what to do you can make pull-request with support of such situations
